
# Using Bind mount to create connection with this config file to config file od nginx in docker
# docker run -d \
# -p 9999:9999 \
# --name nginx-loadbalancer \
# -v /Users/dhanush/Documents/infra/devops/nginx/nginx.conf:/etc/nginx/nginx.conf \
# nginx

# worker_processes  <worker_number>;
# worker_processes - it controls the number of worker processes
# It controls how may nginx spawns to run to handle requests
# Instead of creating new process for each request, it can reuse the existing process
# It handles requests via single thread through event loop.
# worker_processes is number of worker threads it creates  that runs independently
# nginx allows to use all cpu cores effectively
# auto - detects the number of cpu cores and assigns based on the availablity

# worker_connections  <number>;
# It controls the number of maximum connections that can be handled per worker process simultaneously
# Maximum number of connections increases the maximum memory usage


# listens on port 80 by default
# srver_name - ip/domain name of the server
# location - path of the server . it will apply to all requests that match the path

# proxy_pass - forward the request to another server (reverse proxy)
# Upstream server - server that handles the request from the client
# Downstream server - server that handles the request to the client

# least_conn - select the server with least number of connections
# If least_conn is not mentioned, it will use Round Robin algorithm

worker_processes  auto;

events {
    worker_connections  1024;
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream nginx_cluster {
        least_conn;
        # server localhost:9000;
        # server localhost:9001;
        # server localhost:9002;
        server host.docker.internal:9000;
        server host.docker.internal:9001;
        server host.docker.internal:9002;
    }

    server {
        listen 9999;
        # for secure connection
        # listen 443 ssl;
        
        # ssl file path
        # ssl_certificate     /etc/ssl/cert.pem;
        # ssl_certificate_key /etc/ssl/key.pem;

        server_name  localhost;
        location / {
            proxy_pass http://nginx_cluster;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;

        }
    }
}