# K8s
# Pod manifest file - yml file to create a pod
apiVersion: v1

kind: Pod

metadata:
  name: mypod
  labels:
    app: myapp

spec:
  containers:
    - name: mycontainer
      image: my_node_app
      imagePullPolicy: Never
      # If imagePullPolicy is not set, the default is Always which will always pull the image from the registry
      # TO use a local image, set the imagePullPolicy to Never
      ports:
        - containerPort: 3000
